package com.example.myexcltoddta.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myexcltoddta.DetonatorData;

import com.example.myexcltoddta.Dao.DetonatorDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig detonatorDataDaoConfig;

    private final DetonatorDataDao detonatorDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        detonatorDataDaoConfig = daoConfigMap.get(DetonatorDataDao.class).clone();
        detonatorDataDaoConfig.initIdentityScope(type);

        detonatorDataDao = new DetonatorDataDao(detonatorDataDaoConfig, this);

        registerDao(DetonatorData.class, detonatorDataDao);
    }
    
    public void clear() {
        detonatorDataDaoConfig.clearIdentityScope();
    }

    public DetonatorDataDao getDetonatorDataDao() {
        return detonatorDataDao;
    }

}
